/*Example message arrays for the two demo scrollers*/

var pausecontent=new Array()

pausecontent[0]='<a href="/news_bn.htm" class="tlink"><img src="images/bnetnews_banner.jpg" border="0" alt="news@buddhanet" /></a><br />Visit our new Buddhist news and events page: <a href="/news_bn.htm" class="tlink" style="display:inline;">news@buddhanet</a>'
pausecontent[1]='<img src="images/bdr.png" align="right" border="0" /><a href="/resources/" class="tlink">NEW! Buddhist Digital Resources</a><br><br>This collection of Buddhist Digital Resources brings together a representative selection of Buddhist electronic resources from all the traditions on the Internet. This will help to make the Buddha’s teachings more accessible and a valuable research tool and guide for students and those interested in the Buddha’s Dharma.'
pausecontent[2]='<a href="http://www.buddhanet.info/wbd/" class="tlink">BuddhaNet’s World Buddhist Directory</a><br /><img src="images/buddhanet2010/wbd_icon.gif" align="right" border="0" />Buddhist organisations are welcome to include/update their organisation’s information in the database.<br /><br />If you wish to select one of the thousands of directory records to update, or to add a new one, follow this link <a href="http://www.buddhanet.info/wbd/updateselect.php">http://www.buddhanet.info/wbd/updateselect.php</a>'
pausecontent[3]='<a href="http://www.buddhistelibrary.org/" class="tlink">Buddhist eLibrary Project</a><img src="images/buddhanet2010/elib_icon.gif" align="right" border="0" /><br />Buddhist organisations are invited to provide digital content from their respective lineage or teacher. This would benefit the worldwide Buddhist community and the dissemination of the Buddha Dharma. Having your content on more than one server makes it more accessible in the case of a server going down, even temporarily.<br /><a href="http://www.buddhistelibrary.org/">http://www.buddhistelibrary.org/</a>'
pausecontent[4]='<a href="/e-store/store.htm" class="tlink">New! A Vipassana Meditation book and CD “The Vipassana Retreat”</a>by Ven. Pannyavaro<br /><br /><img src="images/buddhanet2010/book_icon.gif" align="right" border="0" />Ven Pannyavaro is the resident teaching monk of Bodhi Tree Forest Monastery and webmaster of BuddhaNet.net.<br /><br />Link to: <a href="http://www.buddhanet.net/e-store/store.htm">http://www.buddhanet.net/e-store/store.htm</a>'

